### ISSUE TITLE
Proposal: Separate the protocol's specification from this reference implementation.

### ISSUE THREAD

**Issue by ghost** [mailpile/gui-o-matic#11]
I propose to separate the protocol's specification (PROTOCOL.MD) from this reference implementation. Doing so would enable other projects to claim conformance with specific versions of the protocol.

While gui-o-mac-tic is the current sole alternative implementation, third-party implementations, such as for the Android platform are plausible in the future.

**Comment by BjarniRunar** [comment]
I don't see why the file living in this repo prevents other projects from referencing it...? There should always be a working reference implementation of the protocol, and this is it.

We should start using version numbers at some point though.
